SELECT *FROM Employees

SELECT ROW_NUMBER() OVER(ORDER BY SALARY) 'RANK' ,SALARY FROM Employees
ORDER BY SALARY


SELECT FIRSTNAME 'NAME',RANK() OVER(ORDER BY SALARY)'RANK',SALARY FROM Employees
SELECT JobId '
NAME',RANK() OVER(PARTITION BY JOBID ORDER BY SALARY)'RANK',SALARY FROM Employees
ORDER BY JOBID,SALARY


SELECT FIRSTNAME 'NAME',JobId,DENSE_RANK() OVER(ORDER BY SALARY)'RANK',SALARY FROM Employees
SELECT FIRSTNAME 'NAME',JobId,DENSE_RANK() OVER(PARTITION BY JOBID ORDER BY SALARY)'RANK',SALARY FROM Employees
ORDER BY rank

SELECT *,
 NTILE(5) OVER(ORDER BY SALARY)'part' FROM Employees
 ORDER BY SALARY
SELECT FirstName 'FNAME',JOBID,
 NTILE(3) OVER(PARTITION BY JOBID ORDER BY SALARY)'part' FROM Employees
 ORDER BY SALARY,part



SELECT DepartmentID,salary=SUM(Salary) FROM Employees
GROUP BY DepartmentID


SELECT DepartmentID,salary=SUM(Salary) FROM Employees
GROUP BY ROLLUP (DepartmentID,Salary)

SELECT SUM(SALARY) AS 'total_salary' FROM Employees
SELECT AVG(SALARY) AS 'total_salary' FROM Employees
SELECT COUNT(*) FROM Employees


